FROM python:3.10-slim

WORKDIR /app

# Copiar primero solo requirements.txt para aprovechar la caché de Docker
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

# Ejecutar la app
CMD ["python", "app.py"]